name: Update Upstream From Fork

on:
  push:
    branches:
      - master
      - v1.18
      - v1.17

env:
  GH_TOKEN: ${{ secrets.SYNC_TEST }}
  GH_REPO: ${{ github.repository }}

jobs:
  update-upstream-from-fork:
    name: "Update Upstream From Fork"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add remote for upstream
        run: git remote add upstream https://github.com/solana-labs/sync_test.git
        shell: bash
      - name: Cherry pick from willhickey/master to upstream/master
        run: |
          git fetch --all
          git checkout -b temp_branch remotes/upstream/master
          git cherry-pick remotes/upstream/master..willhickey/master
          git push upstream master
        shell: bash
# TODO the push will fail because or branch protection rules.            
